const data = [
  {
    id: 1,
    name: "Quần Short BW Comfort Sleep",
    category: "Quần",
    price: 100000,
    stock: 5,
    image1: "../Image/Quần Short BW Comfort Sleep 1.webp",
    image2: "../Image/Quần Short BW Comfort Sleep 2.webp",
    image3: "../Image/Quần Short BW Comfort Sleep 3.webp",
  },
  {
    id: 2,
    name: "Áo Polo Color Parallel White",
    category: "Áo",
    price: 350000,
    stock: 4,
    image1: "../Image/Áo Polo Color Parallel White 1.webp",
    image2: "../Image/Áo Polo Color Parallel White 2.webp",
    image3: "../Image/Áo Polo Color Parallel White 3.webp",
  },
  {
    id: 3,
    name: "Áo Khoác Denim Zipper Navy",
    category: "Áo",
    price: 550000,
    stock: 12,
    image1: "../Image/Áo Khoác Denim Zipper Navy 1.webp",
    image2: "../Image/Áo Khoác Denim Zipper Navy 2.webp",
    image3: "../Image/Áo Khoác Denim Zipper Navy 3.webp",
  },
  {
    id: 4,
    name: "Giày Gravi Cap Black",
    category: "Giày",
    price: 850000,
    stock: 6,
    image1: "../Image/Giày Gravi Cap Black 1.webp",
    image2: "../Image/Giày Gravi Cap Black 2.webp",
    image3: "../Image/Giày Gravi Cap Black 3.webp",
  },
  {
    id: 5,
    name: "Quần Short Dailywear Zipper",
    category: "Quần",
    price: 300000,
    stock: 0,
    image1: "../Image/Giày Gravi Cap Black 1.webp",
    image2: "../Image/Giày Gravi Cap Black 2.webp",
    image3: "../Image/Giày Gravi Cap Black 3.webp",
  },
  {
    id: 6,
    name: "Gold Button Cardigan, Black",
    category: "Womens Casualwear",
    price: 167.0,
    stock: 6,
    image1: "../Image/Quần Short Dailywear Zipper 1.webp",
    image2: "../Image/Quần Short Dailywear Zipper 2.webp",
    image3: "../Image/Quần Short Dailywear Zipper 3.webp",
  },
  {
    id: 7,
    name: "Quần Dài Skinny Leather Black",
    category: "Quần",
    price: 500000,
    stock: 5,
    image1: "../Image/Quần Dài Skinny Leather Black 1.webp",
    image2: "../Image/Quần Dài Skinny Leather Black 2.webp",
    image3: "../Image/Quần Dài Skinny Leather Black 3.webp",
  },
  {
    id: 8,
    name: "Giày WB Sole Mint Pull Tab",
    category: "Giày",
    price: 650000,
    stock: 9,
    image1: "../Image/Giày WB Sole Mint Pull Tab 1.webp",
    image2: "../Image/Giày WB Sole Mint Pull Tab 2.webp",
    image3: "../Image/Giày WB Sole Mint Pull Tab 3.webp",
  },
  {
    id: 9,
    name: "Dép Emboss Bounce Slide",
    category: "Giày",
    price: 340000,
    stock: 9,
    image1: "../Image/Dép Emboss Bounce Slide 1.webp",
    image2: "../Image/Dép Emboss Bounce Slice 2.webp",
    image3: "../Image/Dép Emboss Bounce Slice 3.webp",
  },
  {
    id: 10,
    name: "Áo Khoác Dù Diagonal Pocket",
    category: "Áo",
    price: 450000,
    stock: 2,
    image1: "../Image/Áo Khoác Dù Diagonal Pocket 1.webp",
    image2: "../Image/Áo Khoác Dù Diagonal Pocket 2.webp",
    image3: "../Image/Áo Khoác Dù Diagonal Pocket 3.webp",
  },
  {
    id: 11,
    name: "Áo Khoác Leather Press Stud",
    category: "Áo",
    price: 500000,
    stock: 1,
    image1: "../Image/Áo Khoác Leather Press Stud 1.webp",
    image2: "../Image/Áo Khoác Leather Press Stud 2.webp",
    image3: "../Image/Áo Khoác Leather Press Stud 3.webp",
  },
  {
    id: 12,
    name: "Quần Jean Skinny Distressed Paint",
    category: "Quần",
    price: 550000,
    stock: 10,
    image1: "../Image/Quần Jean Skinny Distressed Paint 1.webp",
    image2: "../Image/Quần Jean Skinny Distressed Paint 2.webp",
    image3: "../Image/Quần Jean Skinny Distressed Paint 3.webp",
  },
  {
    id: 13,
    name: "Áo Khoác Bomber 4 Petal Pattern",
    category: "Áo",
    price: 540000,
    stock: 5,
    image1: "../Image/Áo Khoác Bomber 4 Petal Pattern 1.webp",
    image2: "../Image/Áo Khoác Bomber 4 Petal Pattern 2.webp",
    image3: "../Image/Áo Khoác Bomber 4 Petal Pattern 3.webp",
  },
];

export default data;
